version: '3.9'

networks:
  anymails_network:

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    networks:
      - anymails_network
    restart: unless-stopped
    ports:
      - "5080:80"
      - "5081:5341"
    environment:
      ACCEPT_EULA: Y
    volumes:
      - ./docker/seq/data:/data

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - anymails_network
    restart: unless-stopped
    ports:
      - "6379:6379"

  redis-insight:
    image: redislabs/redisinsight:latest
    depends_on:
      - redis
    container_name: redis-insight
    networks:
      - anymails_network
    restart: unless-stopped
    ports:
      - "5082:8001"
    volumes:
      - ./docker/redisinsight:/db
